baseurl      = "https://wesleych3n.github.io/"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"



  # Subtitle for home
  homeSubtitle = "Software engineer"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  enableThemeToggle = true

  PygmentsCodeFences = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  [params.portrait]
    path     = "img/bio-photo.jpg"
    alt      = "Portrait"

  [[params.social]]
    name = "github"
    url = "https://github.com/WesleyCh3n"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "WesleyCh3n"
    subtitle = "Blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd home"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
